name: Validate action
on:
  pull_request:
  push:
  merge_group:
  schedule:
    - cron: '41 5 * * 1'
permissions:
  contents: read
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '24'
          cache: npm
      - run: npm ci --ignore-scripts
      - run: npm run check
  ci-required:
    if: ${{ always() }}
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - env:
          VALIDATION_RESULT: ${{ needs.validate.result }}
        run: test "$VALIDATION_RESULT" = success
